prep-css-box-model- Marlon Adams
adamsmarlon/prep-0622-code-solutions pull request #6
Opened 2022-06-10 00:07 UTC by adamsmarlon

![Screen Shot 2022-06-09 at 4 59 53 PM](https://user-images.githubusercontent.com/104455010/172964768-c4ab9bec-cedd-48f0-9072-dd726535098b.png)

2022-06-10 00:12 UTC, thebearingedge requested changes

2022-06-10 00:12 UTC, thebearingedge commented on prep-css-box-model/styles.css
> +  width: "3x";
Try moving these properties into your rule set for `button` above. Your buttons should look like this with a thin double border.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/7432943/172965426-ccab4256-d826-4afa-a6fe-dab160bfd29c.png">

2022-06-22 12:41 UTC, adamsmarlon reviewed
![Screen Shot 2022-06-22 at 5 38 30 AM](https://user-images.githubusercontent.com/104455010/175031472-8bb43a09-a2b8-47f4-aeb5-32da5f635c3c.png)

2022-06-22 15:20 UTC, thebearingedge approved these changes

2022-06-27 11:48 UTC, merged