prep-css-display- Marlon Adams
adamsmarlon/prep-0622-code-solutions pull request #7
Opened 2022-06-10 01:36 UTC by adamsmarlon

![Screen Shot 2022-06-09 at 6 29 24 PM](https://user-images.githubusercontent.com/104455010/172972689-0d9c3e49-4a25-42d3-a3d6-202a6641915e.png)

2022-06-10 21:33 UTC, thebearingedge requested changes

2022-06-10 21:33 UTC, thebearingedge commented on prep-css-display/index.html
> +  <div>
Hi Marlon, be sure to put all visible content within a `<body>` element.

2022-06-27 09:43 UTC, adamsmarlon commented
![Screen Shot 2022-06-27 at 2 42 51 AM](https://user-images.githubusercontent.com/104455010/175911403-72048f36-f0e0-4de6-b65a-f96e454b68aa.png)

2022-06-27 15:42 UTC, thebearingedge approved these changes

2022-06-27 15:44 UTC, merged