prep-css-flexbox- Marlon Adams
adamsmarlon/prep-0622-code-solutions pull request #8
Opened 2022-06-11 06:25 UTC by adamsmarlon

![Screen Shot 2022-06-10 at 11 16 46 PM](https://user-images.githubusercontent.com/104455010/173176110-f0ff1327-6c5d-4cd5-a361-f8b3c7946c6a.png)
![Screen Shot 2022-06-10 at 11 17 06 PM](https://user-images.githubusercontent.com/104455010/173176114-f0cab22a-cfaf-43c8-93ae-5b6808f20700.png)
![Screen Shot 2022-06-10 at 11 17 25 PM](https://user-images.githubusercontent.com/104455010/173176117-863bf1d1-af95-47dc-a39f-e8ce046df4d2.png)

2022-06-11 16:13 UTC, thebearingedge requested changes

2022-06-11 16:13 UTC, thebearingedge commented on prep-css-flexbox/flex-wrap.html
> +  </style>
Looks like the CSS is missing from this one.

2022-06-11 16:13 UTC, thebearingedge commented on prep-css-flexbox/justify-content.html
> +      flex-basis: 25%;
Double-check each of your HTML documents. The `flex-basis` property only works when applied to children of elements with `display: flex`. Try moving your `flex-basis` to the `.card-wrapper` rule set in each of your documents.

2022-06-27 12:37 UTC, adamsmarlon commented
![Screen Shot 2022-06-27 at 5 11 18 AM](https://user-images.githubusercontent.com/104455010/175943398-c2112af0-903a-4bb4-9830-3f6789cf7fc5.png)
![Screen Shot 2022-06-27 at 5 11 34 AM](https://user-images.githubusercontent.com/104455010/175943407-cf50445d-7726-48ec-957c-b2bdac9ebe75.png)
![Screen Shot 2022-06-27 at 5 11 46 AM](https://user-images.githubusercontent.com/104455010/175943421-5c538bd9-f22f-4223-8f75-da5873c37237.png)
![Screen Shot 2022-06-27 at 5 11 57 AM](https://user-images.githubusercontent.com/104455010/175943434-a6df2a9e-84ce-4bad-83b7-401395d33dd6.png)

2022-06-27 15:43 UTC, thebearingedge approved these changes

2022-06-27 15:44 UTC, merged